package br.com.sulamerica.mecsas.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Entrada implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int valor;
	private java.lang.String carteira;
	private int produto;
	private int grupo;
	private int apolice;
	private int empresa;
	private java.lang.String vida;
	private int idadeDependente;

	private boolean dependente;

	public Entrada() {
	}

	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

	public java.lang.String getCarteira() {
		return this.carteira;
	}

	public void setCarteira(java.lang.String carteira) {
		this.carteira = carteira;
	}

	public int getProduto() {
		return this.produto;
	}

	public void setProduto(int produto) {
		this.produto = produto;
	}

	public int getGrupo() {
		return this.grupo;
	}

	public void setGrupo(int grupo) {
		this.grupo = grupo;
	}

	public int getApolice() {
		return this.apolice;
	}

	public void setApolice(int apolice) {
		this.apolice = apolice;
	}

	public int getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(int empresa) {
		this.empresa = empresa;
	}

	public java.lang.String getVida() {
		return this.vida;
	}

	public void setVida(java.lang.String vida) {
		this.vida = vida;
	}

	public int getIdadeDependente() {
		return this.idadeDependente;
	}

	public void setIdadeDependente(int idadeDependente) {
		this.idadeDependente = idadeDependente;
	}

	public boolean isDependente() {
		return this.dependente;
	}

	public void setDependente(boolean dependente) {
		this.dependente = dependente;
	}

	public Entrada(int valor, java.lang.String carteira, int produto,
			int grupo, int apolice, int empresa, java.lang.String vida,
			int idadeDependente, boolean dependente) {
		this.valor = valor;
		this.carteira = carteira;
		this.produto = produto;
		this.grupo = grupo;
		this.apolice = apolice;
		this.empresa = empresa;
		this.vida = vida;
		this.idadeDependente = idadeDependente;
		this.dependente = dependente;
	}

}