package br.com.sulamerica.mecsas.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resposta implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int errorCode;
	private java.lang.String mensagem;

	public Resposta() {
	}

	public int getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(int errorCode) {
		this.errorCode = errorCode;
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public Resposta(int errorCode, java.lang.String mensagem) {
		this.errorCode = errorCode;
		this.mensagem = mensagem;
	}

}